challenges/web/invoicer/application/config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'

  # Session
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Users
  resources 'users', only: [:new, :create, :edit, :update]

  # Password reset
  resources 'password_resets', only: [:new, :create, :edit, :update]

  # Invoices
  resources 'invoices', only: [:new, :create, :show, :index]
  get "public/invoices/:public_token", to: "invoices#public", as: :public_invoice

  # Metrics
  get '/metrics', to: 'pages#metrics'

  # Help Center
  get 'help-center', to: 'help_center#home'
  get 'help-center/home', to: 'help_center#home'
  get 'help-center/password_reset', to: 'help_center#password_reset'
  get 'help-center/search_invoice', to: 'help_center#search_invoice'
end

challenges/web/invoicer/application/app/models/invoice.rb
require 'securerandom'

class Invoice < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :details, presence: true
  validates :details, length: { maximum: 255 }
  validates :recipient_email, presence: true
  validates :recipient_email, length: { maximum: 255 }
  validates :recipient_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :recipient_name, presence: true
  validates :recipient_name, length: { maximum: 255 }

  before_create do
    assign_secure_token(:public_token, 34)
  end

  private

  def assign_secure_token(column, length)
    attempt = 0
    maximum_attempt = 10
    while attempt < maximum_attempt
      self[column] = SecureRandom.hex(length / 2)
      return unless Invoice.exists?(column => self[column])

      attempt += 1
    end

    raise StandardError, "Could not generate #{column} after #{maximum_attempt} attempts."
  end
end

challenges/web/invoicer/application/app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  skip_before_action :authenticate!, only: [:public]

  def new
    @invoice = current_user.invoices.build
  end

  def create
    if current_user.admin?
      flash[:info] = "#{ENV['SUPPORT_ACCOUNT_NAME']} can not create invoice."
      redirect_to invoices_path
      return
    end

    @invoice = current_user.invoices.build(create_params)
    if @invoice.save
      flash[:success] = 'Invoice successfully created and sent.'
      redirect_to invoices_path
    else
      render :new
    end
  end

  def show
    @invoice = current_user.invoices.find(params[:id])

    render :show
  end

  def index
    @invoices = current_user.invoices.all
    if params[:keyword]
      # keyword = "%#{ActiveRecord::Base.sanitize_sql_like(params[:keyword])}%"
      keyword = "%#{params[:keyword]}%"
      @invoices = @invoices.where(
        "(details LIKE '#{keyword}') OR (recipient_name LIKE '#{keyword}') OR (recipient_email LIKE '#{keyword}')"
      )
    end

    render :index
  end

  def public
    @invoice = Invoice.find_by!(public_token: params[:public_token])

    render :public, layout: 'public'
  end

  private

  def create_params
    params.require(:invoice).permit(:amount, :details, :recipient_email, :recipient_name)
  end
end

challenges/web/invoicer/application/app/helpers/invoices_helper.rb
module InvoicesHelper
end

challenges/web/invoicer/application/app/views/invoices/create.html.erb
<h1>Invoices#create</h1>
<p>Find me in app/views/invoices/create.html.erb</p>

challenges/web/invoicer/application/app/views/invoices/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Invoices</h1>
  <%= link_to "New invoice", new_invoice_path %>
</div>

<p>Here is a list of all the invoices in your account. You can use the search bar to rapidly find an invoice.</p>

<div>
  <form class="form-inline">
    <label class="sr-only" for="keyword">Keyword</label>
    <input type="text" class="form-control mb-2 mr-sm-2" id="keyword" name="keyword" placeholder="Keyword" value="<%= params[:keyword] %>">

    <button type="submit" class="btn btn-primary mb-2">Search</button>
    <%= link_to "Reset", invoices_path, class: "btn btn-link mb-2", role: "button" %>
  </form>
</div>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th>Amount</th>
      <th>Details</th>
      <th>Recipient name</th>
      <th>Recipient email</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.id %></th>
        <td><%= invoice.amount %></td>
        <td><%= truncate(invoice.details, length: 24) %></td>
        <td><%= truncate(invoice.recipient_email, length: 24) %></td>
        <td><%= truncate(invoice.recipient_name, length: 24) %></td>
        <td><%= link_to "View", invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @invoices.empty? %>
 <p class="text-muted text-center">You have no invoice yet.</p>
<% end %>

challenges/web/invoicer/application/app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<p>The invoice will be sent to the recipient email with a public link that inclus the invoice information.</p>

<%= form_for @invoice do |f| %>
  <% if @invoice.errors.any? %>
    <div class="text-danger">
      <h2>Form is invalid</h2>
      <ul>
        <% @invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.text_field :amount, class: "form-control", type: "number", min: "1", required: true, placeholder: "Amount" %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: "form-control", required: true, placeholder: "Details" %>
  </div>
  <div class="form-group">
    <%= f.label :recipient_name %>
    <%= f.text_field :recipient_name, class: "form-control", required: true, placeholder: "Recipient name" %>
  </div>
  <div class="form-group">
    <%= f.label :recipient_email %>
    <%= f.text_field :recipient_email, class: "form-control", type: "email", required: true, placeholder: "Recipient email" %>
  </div>

  <button type="submit" class="btn btn-primary">Create and send</button>
<% end %>

challenges/web/invoicer/application/app/views/invoices/public.html.erb
<h1>Invoice</h1>

<p>Hi <%= @invoice.recipient_name %>, here is your invoice.</p>

<b>Reference number</b>
<p><%= @invoice.id %></p>

<b>Amount</b>
<p><%= @invoice.amount %></p>

<b>Details</b>
<p><%= @invoice.details %></p>

<b>Created at</b>
<p><%= @invoice.created_at %></p>

challenges/web/invoicer/application/app/views/invoices/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Invoice</h1>
  <%= link_to "Public link", public_invoice_url(public_token: @invoice.public_token) %>
</div>

<b>Id</b>
<p><%= @invoice.id %></p>

<b>Amount</b>
<p><%= @invoice.amount %></p>

<b>Details</b>
<p><%= @invoice.details %></p>

<b>Recipient email</b>
<p><%= @invoice.recipient_email %></p>

<b>Recipient name</b>
<p><%= @invoice.recipient_name %></p>

<b>Created at</b>
<p><%= @invoice.created_at %></p>